ArmyTechTaskApp/Models/InvoiceHeader.cs
using System;
using System.Collections.Generic;

namespace ArmyTechTaskApp.Models
{
    public partial class InvoiceHeader
    {
        public InvoiceHeader()
        {
            InvoiceDetails = new HashSet<InvoiceDetail>();
        }

        public long Id { get; set; }
        public string CustomerName { get; set; } = null!;
        public DateTime Invoicedate { get; set; }
        public int? CashierId { get; set; }
        public int BranchId { get; set; }

        public virtual Branch? Branch { get; set; } = null!;
        public virtual Cashier? Cashier { get; set; }
        public virtual ICollection<InvoiceDetail>? InvoiceDetails { get; set; }
    }
}

ArmyTechTaskApp/Controllers/InvoiceDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ArmyTechTaskApp.Models;
using ArmyTechTaskApp.ViewModel;

namespace ArmyTechTaskApp.Controllers
{
    public class InvoiceDetailsController : Controller
    {
        private readonly ArmyTechTaskContext _context;

        public InvoiceDetailsController(ArmyTechTaskContext context)
        {
            _context = context;
        }

        // GET: InvoiceDetails
        public async Task<IActionResult> Index()
        {
            var armyTechTaskContext = _context.InvoiceDetails.Include(i => i.InvoiceHeader);
            return View(await armyTechTaskContext.ToListAsync());
        }

        // GET: InvoiceDetails/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.InvoiceDetails == null)
            {
                return NotFound();
            }

            var invoiceDetail = await _context.InvoiceDetails
                .Include(i => i.InvoiceHeader)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (invoiceDetail == null)
            {
                return NotFound();
            }

            return View(invoiceDetail);
        }

        // GET: InvoiceDetails/Create
        public IActionResult Create(int Customerid) //  customer id
        {
            ViewData["InvoiceHeaderId"] = new SelectList(_context.InvoiceHeaders, "Id", "CustomerName", Customerid);
            return View();
        }

        // POST: InvoiceDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(InvoiceDetailVM model)
        {
            if (ModelState.IsValid)
            {
                var invoice = new InvoiceDetail()
                {
                    InvoiceHeaderId = model.InvoiceHeaderId,
                    ItemCount = model.ItemCount,
                    ItemName = model.ItemName,
                    ItemPrice = model.ItemPrice
                };
                _context.Add(invoice);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            ViewData["InvoiceHeaderId"] = new SelectList(_context.InvoiceHeaders, "Id", "CustomerName", model.InvoiceHeaderId);
            
            return View(model: model);
        }

        // GET: InvoiceDetails/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.InvoiceDetails == null)
            {
                return NotFound();
            }

            var invoiceDetail = await _context.InvoiceDetails.FindAsync(id);
            if (invoiceDetail == null)
            {
                return NotFound();
            }
            ViewData["InvoiceHeaderId"] = new SelectList(_context.InvoiceHeaders, "Id", "Id", invoiceDetail.InvoiceHeaderId);
            return View(invoiceDetail);
        }

        // POST: InvoiceDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,InvoiceHeaderId,ItemName,ItemCount,ItemPrice")] InvoiceDetail invoiceDetail)
        {
            if (id != invoiceDetail.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(invoiceDetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InvoiceDetailExists(invoiceDetail.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["InvoiceHeaderId"] = new SelectList(_context.InvoiceHeaders, "Id", "Id", invoiceDetail.InvoiceHeaderId);
            return View(invoiceDetail);
        }

        // GET: InvoiceDetails/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.InvoiceDetails == null)
            {
                return NotFound();
            }

            var invoiceDetail = await _context.InvoiceDetails
                .Include(i => i.InvoiceHeader)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (invoiceDetail == null)
            {
                return NotFound();
            }

            return View(invoiceDetail);
        }

        // POST: InvoiceDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            long headerid = 0;
            if (_context.InvoiceDetails == null)
            {
                return Problem("Entity set 'ArmyTechTaskContext.InvoiceDetails'  is null.");
            }
            var invoiceDetail = await _context.InvoiceDetails.FindAsync(id);
            headerid = invoiceDetail.InvoiceHeaderId;
            if (invoiceDetail != null)
            {
                _context.InvoiceDetails.Remove(invoiceDetail);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "InvoiceHeaders", new { id = headerid });
        }

        private bool InvoiceDetailExists(long id)
        {
            return _context.InvoiceDetails.Any(e => e.Id == id);
        }
    }
}

ArmyTechTaskApp/Controllers/InvoiceHeadersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ArmyTechTaskApp.Models;

namespace ArmyTechTaskApp.Controllers
{
    public class InvoiceHeadersController : Controller
    {
        private readonly ArmyTechTaskContext _context;

        public InvoiceHeadersController(ArmyTechTaskContext context)
        {
            _context = context;
        }

        // GET: InvoiceHeaders
        public async Task<IActionResult> Index()
        {
            var armyTechTaskContext = _context.InvoiceHeaders.Include(i => i.Branch).Include(i => i.Cashier);
            return View(await armyTechTaskContext.ToListAsync());
        }

        // GET: InvoiceHeaders/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.InvoiceHeaders == null)
            {
                return NotFound();
            }

            var invoiceHeader = await _context.InvoiceHeaders
                .Include(i => i.Branch)
                .Include(i => i.Cashier)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (invoiceHeader == null)
            {
                return NotFound();
            }

            ViewBag.InvoiceDetails = await _context.InvoiceDetails.Where(x => x.InvoiceHeaderId == id).ToListAsync();

            return View(invoiceHeader);
        }

        // GET: InvoiceHeaders/Create
        public IActionResult Create()
        {
            ViewData["BranchId"] = new SelectList(_context.Branches, "Id", "BranchName");
            ViewData["CashierId"] = new SelectList(_context.Cashiers, "Id", "CashierName");
            return View();
        }

        // POST: InvoiceHeaders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(InvoiceHeader invoiceHeader)
        {
            if (ModelState.IsValid)
            {
                
                _context.Add(invoiceHeader);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BranchId"] = new SelectList(_context.Branches, "Id", "BranchName", invoiceHeader.BranchId);
            ViewData["CashierId"] = new SelectList(_context.Cashiers, "Id", "CashierName", invoiceHeader.CashierId);
            return View(invoiceHeader);
        }

        // GET: InvoiceHeaders/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.InvoiceHeaders == null)
            {
                return NotFound();
            }

            var invoiceHeader = await _context.InvoiceHeaders.FindAsync(id);
            if (invoiceHeader == null)
            {
                return NotFound();
            }
            ViewData["BranchId"] = new SelectList(_context.Branches, "Id", "BranchName", invoiceHeader.BranchId);
            ViewData["CashierId"] = new SelectList(_context.Cashiers, "Id", "CashierName", invoiceHeader.CashierId);
            return View(invoiceHeader);
        }

        // POST: InvoiceHeaders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,CustomerName,Invoicedate,CashierId,BranchId")] InvoiceHeader invoiceHeader)
        {
            if (id != invoiceHeader.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(invoiceHeader);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InvoiceHeaderExists(invoiceHeader.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BranchId"] = new SelectList(_context.Branches, "Id", "BranchName", invoiceHeader.BranchId);
            ViewData["CashierId"] = new SelectList(_context.Cashiers, "Id", "CashierName", invoiceHeader.CashierId);
            return View(invoiceHeader);
        }

        // GET: InvoiceHeaders/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.InvoiceHeaders == null)
            {
                return NotFound();
            }

            var invoiceHeader = await _context.InvoiceHeaders
                .Include(i => i.Branch)
                .Include(i => i.Cashier)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (invoiceHeader == null)
            {
                return NotFound();
            }

            return View(invoiceHeader);
        }

        // POST: InvoiceHeaders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.InvoiceHeaders == null)
            {
                return Problem("Entity set 'ArmyTechTaskContext.InvoiceHeaders'  is null.");
            }
            var invoiceHeader = await _context.InvoiceHeaders.FindAsync(id);
            if (invoiceHeader != null)
            {
                _context.InvoiceHeaders.Remove(invoiceHeader);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InvoiceHeaderExists(long id)
        {
            return _context.InvoiceHeaders.Any(e => e.Id == id);
        }
    }
}

ArmyTechTaskApp/Views/InvoiceHeaders/Create.cshtml
@model ArmyTechTaskApp.Models.InvoiceHeader

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>InvoiceHeader</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" asp-controller="InvoiceHeaders">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Invoicedate" class="control-label"></label>
                <input asp-for="Invoicedate" class="form-control" />
                <span asp-validation-for="Invoicedate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cashier" class="control-label"></label>
                <select asp-for="CashierId" class ="form-control" asp-items="ViewBag.CashierId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Branch" class="control-label"></label>
                <select asp-for="BranchId" class ="form-control" asp-items="ViewBag.BranchId"></select>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index"class="btn btn-dark">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ArmyTechTaskApp/Views/InvoiceHeaders/Delete.cshtml
@model ArmyTechTaskApp.Models.InvoiceHeader

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>InvoiceHeader</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Invoicedate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Invoicedate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Branch)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Branch.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cashier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cashier.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-dark">Back to List</a>
    </form>
</div>

ArmyTechTaskApp/Views/InvoiceHeaders/Details.cshtml
@model ArmyTechTaskApp.Models.InvoiceHeader

@{
    ViewData["Title"] = "Details";
    double sum = 0;
}

<h1>Details</h1>

<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Invoicedate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Invoicedate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Branch)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Branch.BranchName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cashier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cashier.CashierName)
        </dd>
    </dl>
</div>
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>item Name</th>
        <th>item Count</th>
        <th>item Price</th>
        <th>item total</th>
        <th>links</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in (List<InvoiceDetail>)ViewBag.InvoiceDetails)
    {
        sum += item.ItemPrice * item.ItemCount;
        <tr>
            <td>@item.ItemName</td>
            <td>@item.ItemCount</td>
            <td>@item.ItemPrice</td>
            <td>@(item.ItemPrice*item.ItemCount)</td>
            <td>
                <a asp-action="Edit" asp-controller="InvoiceDetails" class="btn btn-outline-success rounded-pill " asp-route-id="@item.Id">Edit</a> |
              
                <a asp-action="Delete" asp-controller="InvoiceDetails" class="btn btn-outline-danger rounded-pill "asp-route-id="@item.Id">Delete</a>
            </td>

        </tr>
    }
  
    </tbody>
</table>
<p>total invoice :   @sum</p>
      
<br />
<div>
    <a asp-action="Index"class="btn btn-dark">Back to List</a>
</div>

ArmyTechTaskApp/Views/InvoiceHeaders/Edit.cshtml
@model ArmyTechTaskApp.Models.InvoiceHeader

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>InvoiceHeader</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Invoicedate" class="control-label"></label>
                <input asp-for="Invoicedate" class="form-control" />
                <span asp-validation-for="Invoicedate" class="text-danger"></span>
            </div>
           <div class="form-group">
                <label asp-for="Cashier" class="control-label"></label>
                <select asp-for="CashierId" class ="form-control" asp-items="ViewBag.CashierId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Branch" class="control-label"></label>
                <select asp-for="BranchId" class ="form-control" asp-items="ViewBag.BranchId"></select>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary " />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index" class="btn btn-dark">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ArmyTechTaskApp/Views/InvoiceHeaders/Index.cshtml
@model IEnumerable<ArmyTechTaskApp.Models.InvoiceHeader>

@{
    ViewData["Title"] = "Index";
}

<h1>Invoices</h1>
<link rel="stylesheet" href=" https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css"/>
<p>
    <a asp-action="Create" class="btn btn-primary">New Customer</a>|
     <a asp-action="Create" class="btn btn-primary"  method="post" asp-controller="InvoiceDetails">New Invoice </a>
</p>
<table id="tableIndex" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Invoicedate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Branch)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cashier)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Invoicedate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Branch.BranchName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cashier.CashierName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-success rounded-pill">Edit</a> |
                                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-secondary rounded-pill">Details</a> |

                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger rounded-pill">Delete</a>|
                 <a asp-action="Create" asp-controller="InvoiceDetails" asp-route-id="@item.Id"class="btn btn-outline-info rounded-pill">Add Invoice</a>
            </td>
        </tr>
}
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
    $('#myTable').DataTable();
             });
        </script>

 